version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile-prod
    command: sh -c "node app.js"
    ports:
      - ${PORT:-3000}:3000
    volumes:
      - ./:/home/xpub
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      PGHOST: postgres
      PGUSER: $USER

  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: $USER
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./scripts/test.sql:/docker-entrypoint-initdb.d/test.sql

volumes:
  postgres-volume:

